### ISSUE TITLE
Incorrect query with array spread parsed and allowed

### ISSUE THREAD

**Issue by golergka** [adelsz/pgtyped#168]
# Steps to reproduce

I create two example queries:

```Typescript
const example1 = sql`
	SELECT id
	FROM users
	WHERE id IN $$userIDs
`

const example2 = sql`
	SELECT id
	FROM users
	WHERE id IN ($$userIDs)
`
```

And generate types for them with pgtyped CLI tool.

# Expected result

I expect that pgtyped will catch all query errors in type generation phase, and therefore, one of the queries above will produce errors.

# Actual result

Both queries generate types without any errors.

Moreso, when called like this:

```Typescript
await example1.run({
	userIDs: [1]
}, pg)
await example2.run({
	userIDs: [1]
}, pg)
```

Both provide no runtime errors. Only when provided with array arguments of length more than 1, do they end up with errors.

# Discussion

This is related to [his issue](https://github.com/adelsz/pgtyped/issues/150) I brought forward before. It seems that with simple array spreads, pgtyped does indeed create a set of parens for the array, but does not for array object spread. When I write things like `IN $$userIDs` it's easy to make a mistake and write `IN ($$userIDs)` instead, and if a system that I expect would behave like type checker will not catch this error, and it won't even be apparent with some easy test data (like arrays with one element), this could easily become a source of some serious errors in production.

Aside from fixing this bug, I would like to humbly suggest to review the basic rules for spreading arrays and objects, making them consistent and emphasize these rules in the documentation. Of course, making such mistakes is in the end is my responsibility as a developer, but I believe that truly awesome tools know what kind of silly mistakes developers could routinely make, and prevent them — and it would help make pgtyped even more awesome.

**Comment by adelsz** [comment]
Thanks for filing this issue @golergka

The problem here was that for postgres all of the following queries are equivalent:
```sql
SELECT id FROM users WHERE id IN (1);
SELECT id FROM users WHERE id IN ((1));
SELECT id FROM users WHERE id IN (((1)));
```

When doing type inference pgTyped first does a substitution:
```sql
--- original query
SELECT id FROM users WHERE id IN ($$userIDs)
--- after processing
SELECT id FROM users WHERE id IN (($1))
```
This makes the query pass pgTyped without errors.

An easy way to fix this is to make pgTyped substitute two instances instead:
```sql
--- original query
SELECT id FROM users WHERE id IN ($$userIDs)
--- after processing
SELECT id FROM users WHERE id IN (($1, $1))
```
Such a transformation will throw an error as expected.
I will make sure to include this fix in the next minor release.

> I would like to humbly suggest to review the basic rules for spreading arrays and objects, making them consistent and emphasize these rules in the documentation.
With a fix for the above edgecase landing soon do you think a further improvement of the array/object spread syntax will be useful?

Regarding docs, I really appreciate all suggestions there, as pgTyped's author it is harder for me to spot their deficiencies than it is for our users. I will definitely have another look prior to next release though.

**Comment by golergka** [comment]
I've given the issue some thought. So, there are four parameter substitution patterns: simple parameters, array spread, object pick and array spread and pick. In all of them, except the last, pgtyped inserts the surrounding parens on it's own, which creates a bit of confusion.

May be a dense cheatsheet like this would be helpful? https://github.com/adelsz/pgtyped/pull/178

**Comment by adelsz** [comment]
Thanks again for improving the docs @golergka. Closing this issue.
