### ISSUE TITLE
Returning only first result

### ISSUE THREAD

**Issue by ludusrusso** [adelsz/pgtyped#234]
It would be nice, when developing, to inform the generated code to return only the first result of the query. This would be useful when I have a query that I know returns only a single element, something like;

```sql
/*
  @name getUserById
  @returns single
*/

SELECT * FROM users WHERE id=:id;
```

While I now that this query generates only one result, the generated code returns and array of objects.

**Comment by golergka** [comment]
In fact, your query can return 0 or 1 results. There should be separate types for queries like this, and queries like `SELECT COUNT(*) as "count" FROM users`, which always return exactly 1 result.

**Comment by mgreenw** [comment]
@ludusrusso The pattern I prefer in this case is to destructure the first element in the resultant array and check if it exists. 

For example:
```ts
const [user] = await query.run({ id }, client);

if (!user) {
  throw new Error("User not found");
}

// Use the user
```

This works especially well when combined when Typescript has ["noUncheckedIndexedAccess"](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) set to `true`, which means that `user` will either be the type of a user or `undefined` when it is destructured.

With this pattern available, I don't think it's necessary for `pgtyped` to implement a feature to return a single element instead of an array.

**Comment by adelsz** [comment]
Agree with @mgreenw. Also, such checks can be implemented both at run and compile time by wrapping the `query.run` method.
