### ISSUE TITLE
support postgres scram-sha-256 authentication method

### ISSUE THREAD

**Issue by AlexHorstkoetter** [adelsz/pgtyped#235]
After I switched Postgres from Linux to Windows, pgtyped couldn't connect to postgres anymore and timed out with an "read ECONNRESET" error. According to the Postgres log the authentication timed out. After quite some digging I found that the default password hashing method was changed from MD5 to scram-sha-256 in newer versions of postgres and pgtyped does not seem to support the new method yet (at least it is not listed in query/src/actions.ts startup() ).
Changing the postgres passsword hashing to md5 fixes the problem but it would be much nicer if it would work out-of-the-box or at result in a more useful error message.

p.s. pgtyped is awesome, great job

**Comment by MegaCookie** [comment]
I quickly hacked a simple implementation of the scram-sha-256 implementation based on the actual [node-postgres](https://github.com/brianc/node-postgres) which I will add to my fork soon (and edit this post). It still need to refactor, to actually make sure it follows the same code style.

I am not sure if this is answered already, but @adelsz why did you implement your own wire TCP protocol to talk with PostgreSQL instead of using node-postgres for example?

**Comment by adelsz** [comment]
Thanks for the PR @MegaCookie! I will be taking a look into it soon.

> I am not sure if this is answered already, but @adelsz why did you implement your own wire TCP protocol library to talk with PostgreSQL instead of using node-postgres for example?

Back when I implemented the wire library I couldn't find a good TS native package that provided low-level commands for interacting with PostgreSQL. We use these low level [commands](https://www.postgresql.org/docs/9.3/protocol-message-formats.html) (like the `Describe` command) to fetch type data from Postgres. Another reason was to potentially evolve PgTyped into a self-contained Postgres client at some point.

**Comment by bag-man** [comment]
+1 have also struggled with this! Using postgres 13 is the fix, but would be good to not have that restriction.
