### ISSUE TITLE
[feature request] insert/update params type nullability

### ISSUE THREAD

**Issue by m-ronchi** [adelsz/pgtyped#242]
currently, input types for insert and update queries (the ones in `SET column_name = :param`) are always defined as `param: Type | null | void`.

ideally, pgtyped should infer nullability. but you said in #118 that can't be done easily.

you could implement a new syntax for explicitly specifying nullability and generate nullable types accordingly, e.g:
- `:param` -> current behaviour (no breaking changes), emit warning if ambiguous (possibly behind a flag)
- `:?param` or `:param?` -> force nullable type
- `:!param` or `:param!` -> force non nullable type

also, when you generate properties as `name: Type | null | void`, parameters are required by TS (have to explicitly set the to undefined), it would be better to generate them as `name?: Type | null` (`undefined` is still accepted by TS, but you can also omit that property).

**Comment by golergka** [comment]
Explicit annotations for things that Pgtyped cannot infere sound like a great idea. May be they could also be used to denote amount of retrieved rows (1, 0 or 1, 0, 1 or more)?

**Comment by JohnnyCrazy** [comment]
I was quite intrigued by the idea and think this would be a great expansion for `pgtyped`. Since I wanted to dive into pgtyped anyway, I went ahead and created a small prototype (https://github.com/JohnnyCrazy/pgtyped/tree/param-nullability) with the following syntax:

### Scalar

```sql
/* @name GetAllComments */
SELECT * FROM book_comments WHERE id = :id! OR user_id = :id;
```

Since `:id` is required at least once, it will **not** be nullable:

```
export interface IGetAllCommentsParams {
  id: number;
}
```

### Array

```sql
/*
  @name GetAllCommentsByIds
  @param ids -> (...)
*/
SELECT * FROM book_comments WHERE id in :ids!;
```

We can also handle array spread syntax in the query itself

```
export interface IGetAllCommentsByIdsParams {
  ids: readonly (number)[];
}
```

### Pick 

```sql
/*
  @name InsertSingleComment
  @param comment -> (userId!, commentBody)
*/
INSERT INTO book_comments (user_id, body) VALUES :comment;
```

In the pick syntax we have to declare required keys in the param declaration, since the object itself is required anyway

```
export interface IInsertSingleCommentParams {
  comment: {
    userId: number,
    commentBody: string | null | void
  };
}
```

### Array Pick 

```sql
/*
  @name InsertBooks
  @param books -> ((rank!, name!, authorId)...)
*/
INSERT INTO books (rank, name, author_id)
VALUES :books RETURNING id as book_id;
```

In the pick syntax we have to declare required keys in the param declaration, since the array itself is required anyway
```
export interface IInsertBooksParams {
  books: readonly ({
    rank: number,
    name: string,
    authorId: number | null | void
  })[];
}
```

The `TS` version is pretty much the same principle, `$userId! $$users! $user(id!, body)`. I didn't find any mayor dealbreaks and it should be non-breaking (I don't think `!` behind a variable is any valid postgres query). So in the end depends on @adelsz if he would like to see this in the project, I could clean up the branch and PR it.

**Comment by delaneyj** [comment]
One nice thing about the current use of `:name` is it still allows for direct c/p usage in tools such as DBeaver.  In that vain I'd love to see.

`:name` === `name: T`
`?name` === `name?: T | null`

which would still allow outside tooling but be very clear and easy to write.

**Comment by JohnnyCrazy** [comment]
@delaneyj That however would be a huge breaking change. I will test around with different styles, maybe also sth like `:?name`, but the main problem is that variable substitution via `:` is not a standard AFAIK, so every tool behaves differently.

**Comment by delaneyj** [comment]
> That however would be a huge breaking change. 
Agreed, definitely would be a major semver change.  But having something that works with all major tooling that is concise seems worth it imho.

**Comment by adelsz** [comment]
Thanks @JohnnyCrazy, that is a great proposal. I like the suffix modificator approach and will be happy to review & merge if you are willing to put together a draft PR.

**Comment by ferntheplant** [comment]
I know the non-nullable `:variable!` feature got merged and I love it but I wanted to check in on the `:variable?` syntax. Right now a nullable query param is still required on the TS param type like `{ variable: T | null | void }`. I would appreciate if, like @delaneyj reccomended, there was a way to get the output type to be `{ variable?: T | null | void }` so I don't need to put all the nullable params as keys on my input objects.

I would love to do something like below:
```sql
/* 
    @name insertUser
    @param users -> ((id!, optionalField?)...)
 */
INSERT INTO users (id, optional_field)
    VALUES :users;
```

```typescript
const users = [
    {
      id: 1
    },
    {
      id: 2,
      optionalField: 'foo',
    }
]

await query.run(users, client)
```
But right now I need to specify `optionalField: null` on the first user in the array above to meet the param type requirements.
