### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by mcchrish** [adelsz/pgtyped#262]
Pgtyped + Deno in theory sounds like a great match but I do wonder how easy it is to make this lib compatible with Deno runtime.

Luckily, the most developed deno pg client so far is based on the most used node pg client. https://deno-postgres.com

**Comment by adelsz** [comment]
This would be great to have. I am not sure how much effort it would be to make it Deno compatible without publishing a new library.

**Comment by adelsz** [comment]
Closing, Deno is a non priority for now.

**Comment by not-rusty** [comment]
For those poor souls that are looking into this:

Just add this into your `deno.jsonc`

```json
    "imports": {
        "@pgtyped/runtime": "npm:@pgtyped/runtime@2.0.0"
    }
```

This will remap the imports, and deno will be able to correctly fetch teh @pgtyped/runtime dependency.

And, if you want to use the deno postgres client, this works for me:

```typescript
import { Client } from 'https://deno.land/x/postgres@v0.17.0/mod.ts'

const client = new Client({
    // ...
})
await client.connect()

const db = {
    query(sql: string, bindings: any[]): Promise<{ rows: any[]}> {
        return client.queryArray(sql, bindings)
    }
}

/// later
const results = await queries.getUserOrSomething.run({ user_id: 0 }, db)
```

and that's it!

**Comment by not-rusty** [comment]
I just discovered this, so maybe there's a caveat? If it works, solving this issue would be as simple as mentioning in the docs that you should modify the `deno.jsonc` docs.

**Comment by lpil** [comment]
Thank you! It would be fab if we could get this into the documenation

**Comment by SebastienGllmt** [comment]
Unfortunately pgtyped 2.0 broke support for Deno because it started using [Piscina](https://github.com/piscinajs/piscina) which internally uses a nodejs `perf_hook` which is [not yet supported by deno](https://github.com/denoland/deno/issues/20961#issuecomment-2492828204)

There are two ways to solve this:
1. Wait for Deno to add the missing function to their node API implementation
2. Set `recordTiming: false` in the Piscina constructor [here](https://github.com/adelsz/pgtyped/blob/402dd936970b426084c90714f0d9ca3dd68a5fe9/packages/cli/src/index.ts#L28-L32) (requires pgtyped author to make this change)

A warning on solution (2): pgtyped is actually using an old version version of Piscina. If the version used gets upgraded by https://github.com/adelsz/pgtyped/pull/593 you have to instead change the parameter to `enableHistogram: false`
