### ISSUE TITLE
`Array spread and pick` unexpected type when using `select from values`

### ISSUE THREAD

**Issue by mrjackdavis** [adelsz/pgtyped#313]
Firstly, great project. Great work. A+

I'm having difficulties with types when using `Array spread and pick` and `select * from (values :param) my_vals`. Here's a simplified example:

```sql
/*
  @name myQuery
  @param the_param -> ((num)...)
*/

insert into app.my_table (num_col)

select
  -- this fn is the reason I need `select from values` instead of just `values :the_param` like the docs
  some_fn(
    my_vals.num :: double precision
  )
from (
  values :the_param
) my_vals (
  num
);
```

`pgtyped` infers the type for `the_param` as `{ num:  string | null | void }[]` whereas I want `{ num: number }[]`.

It makes sense because I'm casting `my_vals.num` to `double precision` in the select portion of the query.

How do I have `the_param` to be typed as `{ num: number }[]`? Do you have any advice here?

**Comment by RyanDurk** [comment]
I have a similar problem with a boolean type (inferred type is <string | null | void> instead of just <boolean>).

`/*
  @name insertVendors
  @param vendors -> ((name, is_enabled)...)
*/
INSERT INTO vendor (owner_name, name, is_enabled)
  SELECT
  :owner_name, t1.name, t1.is_enabled
  FROM (VALUES :vendors) t1 (name, is_enabled)
RETURNING id, name, is_enabled::boolean;`

**Comment by adelsz** [comment]
There is ongoing work on a workaround here https://github.com/adelsz/pgtyped/pull/377 that allows you to force remove field nullability.
Also adding this to the meta issue of inference bug in the PG engine #375.
