### ISSUE TITLE
BUG: camel case column names has incorrect outputs for columns including numbers

### ISSUE THREAD

**Issue by ferntheplant** [adelsz/pgtyped#433]
Given the following query
```SQL
/* @name getUser */
SELECT
  users.is_10_years_old
FROM users
```
Pgtyped outputs the following query return type 
```typescript
/** 'getUser' return type */
export interface IGetUserResult {
  is_10YearsOld: string | null;
}
```
The `is_10YearsOld` key should be `is10YearsOld` according to `lodash.camelCase` and my own intuition. I see `pgtyped` is using the NPM package `camel-case` package which actually disagrees with `lodash` and `camelcase` (another NPM package) which both have more weekly installs than `camel-case`, if that is a reasonable heuristic for standard convention.

**Comment by adelsz** [comment]
Camelcase in general isn't great at dealing with numbers.
It is unclear how to differentiate between `exercise_1_12` and `exercise_11_2` if both are camelcased to `exercise112`. The [camel-case](https://www.npmjs.com/package/camel-case) package supports merging numbers as well, but I am not sure if this is a good solution.

I would prefer to keep the behavior as is because it keep the result unambiguous.
The general recommendation for such cases would be to avoid putting numbers in field names, ex. `isTenYearsOld`.
