### ISSUE TITLE
Support for additional Postgres types (json, jsonb, bytea, etc)

### ISSUE THREAD

**Issue by silasdavis** [adelsz/pgtyped#45]
Thanks for the library :)

Looking at https://github.com/adelsz/pgtyped/blob/master/packages/cli/src/generator.ts#L20-L58 it seems like the generator does not support a few types that are used quite often. Namely `json/jsonb` and `bytea`. What would it take to add support? Depending on the complexity I might be able to find time to have a go at implementing.

For reference the complete list of PG types: https://www.postgresql.org/docs/current/datatype.html - full support would be challenging...

Perhaps it would be possible to fall back to a generated `Buffer` or `string` Typescript type for currently unsupported types. The `Buffer` fallback would work for `bytea`. `json` would be something like `type Json = null | boolean | number | string | Json[] | { [key: string]: Json }`

**Comment by adelsz** [comment]
Thanks @silasdavis !
You are right, some common types aren't supported at the moment.
`json/jsonb` and `bytea` should be quite simple to add, you just need to add them to the `typeMap` object.
Composite types and arrays are a bit trickier to implement because they are higher order types. Multiple type resolution queries will be needed here.

The end goal is to support all types in the PGSQL spec and provide the user with a config option to override certain mappings. Ex. some user might want to map `bytea` to a `Uint8Array` instead of a `Buffer`.

I think adding support for `json/jsonb` and `bytea` should be a good first step.
