### ISSUE TITLE
Support for node-postgres QueryConfig

### ISSUE THREAD

**Issue by adamochayon** [adelsz/pgtyped#83]
Hey!
This package suite seems very useful and well done, so first of all thanks for the good work!

I was wondering, as it seems the package relies upon use in conjunction with `node-postgres`, why redefine the types as opposed to using the ones provided from `pg`.

For example, why don't the `processQueryAST`/`processQueryString` functions return the `pg` type `QueryConfig` or `Submittable`? https://github.com/brianc/node-postgres-docs/blob/master/content/api/2-client.mdx#clientqueryconfig-queryconfig-callback-err-error-result-result--void--void

This will allow for better extensibility and integration with the pg client, which is currently wrapped - One example that comes to mind is that it is currently  not easy to leverage pg support for prepared statements (which can be done simply by adding a `name` to the `QueryConfig`).

**Comment by adelsz** [comment]
Hi, thanks!

Looks like the relevant type [definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9ebc05c7f56fff8d8d8a59674a53d7095f9d710d/types/pg/index.d.ts#L176) for the `query` method is:
```ts
function query<R extends QueryResultRow = any, I extends any[] = any[]>(
  queryConfig: QueryConfig<I>,
): Promise<QueryResult<R>>;
```
In this definition the type of `QueryConfig<I>` doesn't determine the result type `QueryResult<R>`, so it isn't sufficient for fully typing a query. This is why we use a wrapper around it.

I think a better solution is to provide a way for our `query.run` method to pass extra arguments to the underlying executor, so that users can create adapters for their DB client of choice.

**Comment by adamochayon** [comment]
Yep, looks like that type definition won't cut it for passing into query.

Maybe an option is making `run` accept an additional `queryConfig` which is a partial of the `QueryConfig` object, which can then be spread directly into the db `query` function.

I'll create a small PR to demonstrate what I mean, let me know what you think.
